package errorcode

const (
	ORDER_NOT_FOUND            = "ORDER_NOT_FOUND"
	INVALID_INPUT_CREATE_ORDER = "INVALID_INPUT_CREATE_ORDER"
	INVALID_INPUT_EDIT_ORDER   = "INVALID_INPUT_CREATE_ORDER"
	ORDER_DELETE_FAILED        = "ORDER_DELETE_FAILED"
)
